"""FROZEN LOCAL STAND-IN for ``renquant_common.cost_model`` (crypto RFC D-C8a).

Definitions below are BYTE-IDENTICAL to the canonical module shipped by the
companion renquant-common PR (feat/net-cost-primitives) — same classes, same
functions, same frozen conventions; only this header differs. It exists so
the model-side fee gate (D-C8b) soft-consumes the canonical when the
installed renquant-common ships it and otherwise degrades to identical local
math — merge order stays free with no pin bump (the pipeline#183 /
base-data#41 soft-consume pattern).

Do NOT edit this file independently: semantics are pinned by the parity test
(``tests/crypto/test_fee_gate.py::test_fallback_parity_with_common``), and
the file is DELETED once renquant-model's pin guarantees a renquant-common
release carrying ``cost_model``. Import via
``renquant_model_crypto.fee_gate.cost_model`` — never directly.
"""
from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Iterable, Mapping, Sequence

__all__ = [
    "CostModelSpec",
    "TurnoverBreakdown",
    "apply_costs_to_period_returns",
    "per_side_cost_bps",
    "realized_traded_fraction",
    "rebalance_cost_fraction",
    "round_trip_cost_bps",
    "turnover_breakdown",
]

_BPS = 1e4


def _require_finite_nonneg(name: str, value: float) -> float:
    v = float(value)
    if not math.isfinite(v) or v < 0.0:
        raise ValueError(f"CostModelSpec.{name} must be finite and >= 0, got {value!r}")
    return v


@dataclass(frozen=True)
class CostModelSpec:
    """Per-side cost components, all in basis points.

    :param fee_bps: venue fee per side (taker or maker — the caller picks
        which schedule applies to the flow being modeled).
    :param spread_bps: FULL quoted bid-ask spread; half is paid per side.
    :param slippage_bps: per-side impact/slippage allowance BEYOND the
        half-spread (e.g. a Stage-0 ex-ante bound from quote-depth-vs-size).
    :param increment_rounding_bps: per-side loss bound from quantity
        truncation to a venue's minimum trade increment.

    Every component defaults to 0 so a fee-only model is spelled
    ``CostModelSpec(fee_bps=...)`` with nothing implicit.
    """

    fee_bps: float = 0.0
    spread_bps: float = 0.0
    slippage_bps: float = 0.0
    increment_rounding_bps: float = 0.0

    def __post_init__(self) -> None:
        for name in ("fee_bps", "spread_bps", "slippage_bps", "increment_rounding_bps"):
            object.__setattr__(self, name, _require_finite_nonneg(name, getattr(self, name)))


def per_side_cost_bps(spec: CostModelSpec) -> float:
    """Total cost of ONE side (one fill), in bps of the traded notional.

    ``fee + spread/2 + slippage + increment_rounding``.
    """
    return spec.fee_bps + spec.spread_bps / 2.0 + spec.slippage_bps + spec.increment_rounding_bps


def round_trip_cost_bps(spec: CostModelSpec) -> float:
    """Cost of a full round trip (buy then sell), in bps: 2 x per-side."""
    return 2.0 * per_side_cost_bps(spec)


@dataclass(frozen=True)
class TurnoverBreakdown:
    """Turnover between two weight vectors, every convention named.

    * ``buy_fraction``: sum of positive weight increases (NAV fraction bought).
    * ``sell_fraction``: sum of weight decreases, as a positive number.
    * ``traded_fraction``: ``buy_fraction + sell_fraction`` — the quantity
      per-side costs apply to.
    * ``one_sided``: ``traded_fraction / 2`` — the conventional turnover
      statistic; NEVER multiply costs by this (that silently halves them).
    """

    buy_fraction: float
    sell_fraction: float

    @property
    def traded_fraction(self) -> float:
        return self.buy_fraction + self.sell_fraction

    @property
    def one_sided(self) -> float:
        return self.traded_fraction / 2.0


def _validated_weights(name: str, weights: Mapping[str, float]) -> dict[str, float]:
    out: dict[str, float] = {}
    for key, value in weights.items():
        v = float(value)
        if not math.isfinite(v):
            raise ValueError(f"{name}[{key!r}] must be finite, got {value!r}")
        out[str(key)] = v
    return out


def turnover_breakdown(
    prev_weights: Mapping[str, float],
    next_weights: Mapping[str, float],
) -> TurnoverBreakdown:
    """Buy/sell/traded fractions to move ``prev_weights`` -> ``next_weights``.

    Symbols absent from a mapping have weight 0 (a new position is all buy;
    a dropped position is all sell). Weights may be any finite floats; the
    caller owns whether they sum to 1.
    """
    prev = _validated_weights("prev_weights", prev_weights)
    nxt = _validated_weights("next_weights", next_weights)
    buys = 0.0
    sells = 0.0
    for key in set(prev) | set(nxt):
        delta = nxt.get(key, 0.0) - prev.get(key, 0.0)
        if delta > 0:
            buys += delta
        else:
            sells += -delta
    return TurnoverBreakdown(buy_fraction=buys, sell_fraction=sells)


def rebalance_cost_fraction(
    prev_weights: Mapping[str, float],
    next_weights: Mapping[str, float],
    spec: CostModelSpec,
) -> float:
    """Cost of one rebalance as a fraction of NAV.

    ``per_side_cost_bps(spec)/1e4 * traded_fraction`` — every traded unit
    (buy or sell) pays the per-side cost exactly once.
    """
    traded = turnover_breakdown(prev_weights, next_weights).traded_fraction
    return per_side_cost_bps(spec) / _BPS * traded


def realized_traded_fraction(intended_traded_fraction: float, fill_ratio: float) -> float:
    """REALIZED traded fraction after partial/zero fills (RFC §4.4).

    An order that rests and never fills is a zero-fee, zero-fill outcome: it
    contributes nothing to costs (this function) and its would-be return
    must equally not be credited by the replay evaluator (the caller's
    obligation, documented at module level). ``fill_ratio`` must lie in
    [0, 1]; anything else is a hard error, never clipped silently.
    """
    intended = float(intended_traded_fraction)
    ratio = float(fill_ratio)
    if not math.isfinite(intended) or intended < 0.0:
        raise ValueError(f"intended_traded_fraction must be finite and >= 0, got {intended_traded_fraction!r}")
    if not math.isfinite(ratio) or not (0.0 <= ratio <= 1.0):
        raise ValueError(f"fill_ratio must lie in [0, 1], got {fill_ratio!r}")
    return intended * ratio


def apply_costs_to_period_returns(
    gross_returns: Sequence[float] | Iterable[float],
    traded_fractions: Sequence[float] | Iterable[float],
    spec: CostModelSpec,
) -> list[float]:
    """Net-of-cost period returns: ``net_t = gross_t - rate * traded_t``.

    ``rate`` is the per-side cost as a fraction (``per_side_cost_bps/1e4``);
    ``traded_fractions[t]`` is the REALIZED traded fraction charged to
    period ``t`` (0 for periods with no rebalance). Lengths must match —
    a silent zip-truncation would drop cost periods, so mismatch is a hard
    error.
    """
    gross = [float(g) for g in gross_returns]
    traded = [float(t) for t in traded_fractions]
    if len(gross) != len(traded):
        raise ValueError(
            f"gross_returns (n={len(gross)}) and traded_fractions (n={len(traded)}) "
            "must have the same length"
        )
    rate = per_side_cost_bps(spec) / _BPS
    net: list[float] = []
    for g, t in zip(gross, traded):
        if not math.isfinite(g):
            raise ValueError(f"gross_returns contains non-finite value {g!r}")
        if not math.isfinite(t) or t < 0.0:
            raise ValueError(f"traded_fractions contains invalid value {t!r} (must be finite, >= 0)")
        net.append(g - rate * t)
    return net
