"""DLinear / NLinear adapter trainer — same interface contract as
``renquant_model_patchtst.hf_trainer.train_single_run`` so the research
harness can swap model families with a single ``--model`` flag.

This trainer is a lightweight pure-torch loop (no HF Trainer dependency
since the linear baselines don't need batched-distributed training or
HF-specific callbacks). It REUSES the model-agnostic pieces of
hf_trainer for fair-comparison parity:

  * ``load_panel_with_split`` (panel I/O + split + train-fit winsor + csrank_norm)
  * ``PerDayDataset`` (per-day, per-ticker sequence batching)
  * ``identity_collator``
  * ``margin_ranking_loss``
  * ``compute_hmm_regime_labels`` (regime context for PerRegimeICCallback parity)

The result: a DLinear/NLinear run uses byte-identical data preprocessing
to a PatchTST run, so the only thing that differs is the model architecture.
That's the fair-comparison framing the merged research plan demands.
"""
from __future__ import annotations

import argparse
import json
import logging
import os
import random
from pathlib import Path
from typing import Any, Callable

import numpy as np
import pandas as pd
import torch
import torch.nn as nn

import renquant_model_patchtst.hf_trainer as hf
from .dlinear import DLinearRanker, NLinearRanker

log = logging.getLogger("linear-trainer")
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")


_MODEL_REGISTRY: dict[str, Callable[..., nn.Module]] = {
    "dlinear": DLinearRanker,
    "nlinear": NLinearRanker,
}


def _set_seed(seed: int) -> None:
    """Deterministic init across torch, numpy, python random."""
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)


def build_parser() -> argparse.ArgumentParser:
    """Mirrors the ``--required`` surface of hf_trainer.build_parser so
    ``ValidateTrainerSurfaceTask`` accepts this trainer as a drop-in.

    The parser keeps PatchTST-only flags (FiLM, cross_stock_attn, NLL
    distributional head) accepted-but-ignored so the same trial argv
    generated by ``_trial_argv`` works for both trainers. The model
    arch is selected by ``--model`` and configured by linear-specific
    knobs (kernel_size for DLinear).
    """
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--cut", required=True)
    p.add_argument("--seed", type=int, required=True)
    p.add_argument("--epochs", type=int, required=True)
    p.add_argument("--device", default="cpu",
                   choices=["auto", "cpu", "mps", "cuda"])
    p.add_argument("--output-dir", required=True)
    p.add_argument("--dataset", required=True)
    p.add_argument("--label", default="fwd_60d_excess")
    p.add_argument("--embargo-days", type=int, default=60)
    p.add_argument("--val-tail-pct", type=float, default=0.10)
    p.add_argument("--strategy-config", default=None)
    p.add_argument("--shuffle-labels", action="store_true")
    p.add_argument("--label-shift-days", type=int, default=0)
    p.add_argument("--exclude-features", default=None)
    p.add_argument("--spy-path", default="data/ohlcv/SPY/1d.parquet")
    # Detector-version plumbing (PR #12) — accept the flag uniformly across
    # trainers so research_pipeline._trial_argv works for both.
    from renquant_common.hmm_regime_labels import (  # noqa: PLC0415
        DETECTOR_VERSION_LEGACY,
        DETECTOR_VERSION_V20260531,
    )
    p.add_argument("--detector-version",
                   default=DETECTOR_VERSION_V20260531,
                   choices=[DETECTOR_VERSION_LEGACY, DETECTOR_VERSION_V20260531])
    # Linear-specific knobs.
    p.add_argument("--model",
                   default="dlinear", choices=sorted(_MODEL_REGISTRY))
    p.add_argument("--seq-len", type=int, default=24,
                   help="Sequence length consumed by the linear model.")
    p.add_argument("--kernel-size", type=int, default=25,
                   help="Moving-average kernel for DLinear's trend extraction. "
                        "Default 25 matches the pinned upstream LTSF-Linear "
                        "DLinear.py:47 at SHA 0c11366. Ignored for NLinear.")
    p.add_argument("--lr", type=float, default=1e-3,
                   help="Adam learning rate. Linear models converge fast; "
                        "1e-3 is a good default for the synthetic + real "
                        "panel sizes used so far.")
    p.add_argument("--weight-decay", type=float, default=0.0,
                   help="Adam weight_decay; default 0 since the linear "
                        "baselines have so few params regularization isn't "
                        "needed for the typical RenQuant panel.")
    p.add_argument("--early-stopping-patience", type=int, default=0,
                   help="Stop training when val_pooled_ic doesn't improve "
                        "for N epochs. 0 disables.")
    # PatchTST-only flags — accept-but-ignore so the harness's --required
    # surface is satisfied uniformly across model families.
    p.add_argument("--film-regime-cond", action="store_true",
                   help="(ignored by linear trainer; PatchTST-only)")
    p.add_argument("--cross-stock-attn", action="store_true",
                   help="(ignored by linear trainer; PatchTST-only)")
    return p


def _ranking_loss_per_day(scores: torch.Tensor, labels: torch.Tensor) -> torch.Tensor:
    """Per-day margin-ranking loss — same formulation as
    hf_trainer.margin_ranking_loss so the loss surface is parity-comparable
    across models."""
    return hf.margin_ranking_loss(scores, labels)


def _pooled_ic(val_preds: pd.DataFrame) -> float:
    """Mean per-day Spearman IC across val dates. Matches
    research_pipeline._daily_ic semantics."""
    from scipy.stats import spearmanr  # noqa: PLC0415
    out: list[float] = []
    for _, g in val_preds.groupby("date"):
        if len(g) < 2:
            continue
        rho, _ = spearmanr(g["pred"], g["label"])
        if np.isfinite(rho):
            out.append(float(rho))
    return float(np.mean(out)) if out else float("nan")


def _per_regime_ic(val_preds: pd.DataFrame) -> dict[str, float]:
    """Per-regime mean IC over val days — same shape as the
    PerRegimeICCallback output so verdict tasks read the same surface."""
    if "regime" not in val_preds.columns or val_preds["regime"].isna().all():
        return {}
    out: dict[str, float] = {}
    from scipy.stats import spearmanr  # noqa: PLC0415
    for regime, g in val_preds.dropna(subset=["regime"]).groupby("regime"):
        ics: list[float] = []
        for _, day in g.groupby("date"):
            if len(day) < 2:
                continue
            rho, _ = spearmanr(day["pred"], day["label"])
            if np.isfinite(rho):
                ics.append(float(rho))
        if ics:
            out[str(regime)] = float(np.mean(ics))
    return out


def _resolve_device(requested: str) -> torch.device:
    if requested == "auto":
        if torch.backends.mps.is_available():
            return torch.device("mps")
        if torch.cuda.is_available():
            return torch.device("cuda")
        return torch.device("cpu")
    return torch.device(requested)


def _build_model(name: str, n_features: int, seq_len: int, kernel_size: int) -> nn.Module:
    cls = _MODEL_REGISTRY[name]
    if name == "dlinear":
        return cls(n_features=n_features, seq_len=seq_len, kernel_size=kernel_size)
    return cls(n_features=n_features, seq_len=seq_len)


def train_single_run(args: argparse.Namespace) -> dict[str, Any]:
    """Drop-in for hf_trainer.train_single_run — same input contract, same
    output shape. The research harness calls this transparently when
    ``--model dlinear|nlinear`` selects the linear trainer."""
    _set_seed(int(args.seed))
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    device = _resolve_device(str(args.device))

    # --- 1. Data via shared hf_trainer plumbing (csrank_norm + train-fit winsor) ---
    exclude_features = (
        [c.strip() for c in args.exclude_features.split(",") if c.strip()]
        if getattr(args, "exclude_features", None) else None
    )
    panel, feat_cols = hf.load_panel_with_split(
        dataset_path=Path(args.dataset),
        cut_name=str(args.cut),
        label_col=str(args.label),
        preprocess=True,
        val_tail_pct=float(args.val_tail_pct),
        embargo_days=int(args.embargo_days),
        exclude_features=exclude_features,
        shuffle_labels=bool(args.shuffle_labels),
        label_shift_days=int(args.label_shift_days),
    )

    # --- 2. Per-day sequence datasets — reuse PerDayDataset ---
    train_ds = hf.PerDayDataset(panel, feat_cols, str(args.label),
                                 int(args.seq_len), "train")
    val_ds = hf.PerDayDataset(panel, feat_cols, str(args.label),
                               int(args.seq_len), "val")
    if len(train_ds) == 0:
        raise RuntimeError(f"train dataset empty after seq_len={args.seq_len}; "
                           f"reduce seq_len or use a larger panel")
    if len(val_ds) == 0:
        raise RuntimeError("val dataset empty — check val_tail_pct + embargo_days")

    # --- 3. Optional HMM regime labels (for per-regime IC, parity with PatchTST) ---
    regime_map: dict[int, str] = {}
    spy_path = Path(args.spy_path)
    if not spy_path.is_absolute() and hasattr(hf, "REPO"):
        spy_path = hf.REPO / spy_path
    if spy_path.exists():
        from renquant_common.hmm_regime_labels import compute_hmm_regime_labels  # noqa: PLC0415
        hmm = compute_hmm_regime_labels(
            spy_path, detector_version=str(args.detector_version),
        )
        regime_map = {pd.Timestamp(d).value: r
                      for d, r in zip(hmm["date"], hmm["regime"])}
        log.info("loaded HMM labels: n_dates=%d", len(regime_map))
    else:
        log.warning("SPY parquet missing at %s — per-regime IC will be empty",
                    spy_path)

    # --- 4. Build model + optimizer ---
    model = _build_model(
        str(args.model),
        n_features=len(feat_cols),
        seq_len=int(args.seq_len),
        kernel_size=int(args.kernel_size),
    ).to(device)
    log.info("%s n_params=%.4fM", model.__class__.__name__,
             sum(p.numel() for p in model.parameters()) / 1e6)
    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=float(args.lr),
        weight_decay=float(args.weight_decay),
    )

    # --- 5. Training loop ---
    best_pooled_ic = float("-inf")
    best_epoch = -1
    no_improve = 0
    epoch_history: list[dict[str, Any]] = []
    val_preds_path = (out_dir
                      / f"{args.model}_{args.cut}_seed{args.seed}_val_preds.parquet")
    summary_path = (out_dir
                    / f"{args.model}_{args.cut}_seed{args.seed}_summary.json")

    for epoch in range(int(args.epochs)):
        # ---- train ----
        model.train()
        train_loss_sum = 0.0
        train_steps = 0
        for day in train_ds.days:
            x = day["past_values"].to(device, dtype=torch.float32)
            y = day["labels"].to(device, dtype=torch.float32)
            if x.size(0) < 2:  # need ≥2 samples for ranking loss
                continue
            scores = model(x)
            loss = _ranking_loss_per_day(scores, y)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            train_loss_sum += float(loss.item())
            train_steps += 1
        train_loss = train_loss_sum / max(train_steps, 1)

        # ---- eval ----
        model.eval()
        preds_rows: list[dict[str, Any]] = []
        with torch.no_grad():
            for day in val_ds.days:
                x = day["past_values"].to(device, dtype=torch.float32)
                y = day["labels"].numpy()
                if x.size(0) == 0:
                    continue
                scores = model(x).cpu().numpy()
                dates_ns = day["dates"]
                tickers = day["tickers"]
                regime_val = (regime_map.get(int(dates_ns[0]), None)
                              if len(dates_ns) > 0 else None)
                for i in range(len(scores)):
                    preds_rows.append({
                        "date": pd.Timestamp(int(dates_ns[i])),
                        "ticker": str(tickers[i]),
                        "pred": float(scores[i]),
                        "label": float(y[i]),
                        "regime": regime_val,
                    })
        val_preds = pd.DataFrame(preds_rows)
        pooled_ic = _pooled_ic(val_preds)
        per_regime = _per_regime_ic(val_preds)
        min_regime = min(per_regime.values()) if per_regime else None
        log.info("epoch=%d train_loss=%.4f val_pooled_ic=%+.4f "
                 "min_regime_ic=%s",
                 epoch, train_loss, pooled_ic,
                 f"{min_regime:+.4f}" if min_regime is not None else "None")
        epoch_history.append({
            "epoch": epoch,
            "train_loss": train_loss,
            "val_pooled_ic": pooled_ic,
            "per_regime_ic": per_regime,
            "min_regime_ic": min_regime,
        })

        # ---- best-model tracking ----
        if pooled_ic > best_pooled_ic:
            best_pooled_ic = pooled_ic
            best_epoch = epoch
            # Persist val_preds at the best epoch (downstream IC computation
            # reads from this parquet, not the per-epoch in-memory df).
            val_preds.to_parquet(val_preds_path, index=False)
            no_improve = 0
        else:
            no_improve += 1
        if (int(args.early_stopping_patience) > 0
                and no_improve >= int(args.early_stopping_patience)):
            log.info("early stopping at epoch %d (patience %d)",
                     epoch, args.early_stopping_patience)
            break

    # --- 6. Summary JSON (shape matches PatchTST's contract surface) ---
    summary = {
        "model": str(args.model),
        "cut": str(args.cut),
        "seed": int(args.seed),
        "epochs_run": len(epoch_history),
        "best_epoch": best_epoch,
        "best_val_ic": float(best_pooled_ic) if best_pooled_ic > float("-inf") else None,
        "best_val_pooled_ic": float(best_pooled_ic) if best_pooled_ic > float("-inf") else None,
        "val_preds_path": str(val_preds_path),
        "epoch_history": epoch_history,
        "n_features": len(feat_cols),
        "n_params": int(sum(p.numel() for p in model.parameters())),
        "feature_cols": feat_cols,
        "device": str(device),
        "detector_version": str(args.detector_version),
        "shuffle_labels": bool(args.shuffle_labels),
        "label_shift_days": int(args.label_shift_days),
    }
    summary_path.write_text(json.dumps(summary, indent=2, default=str))
    return summary


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    summary = train_single_run(args)
    log.info("training done: best_val_pooled_ic=%s",
             summary.get("best_val_pooled_ic"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
