"""Phase A.0 smoke fixture contract tests.

The smoke fixture (`tests/data/smoke_panel.parquet`) is the substrate for
the merged research plan's first kill-gate experiment (`Phase A.0`). These
tests pin the fixture's STATISTICAL properties + the data-pipeline contract
under the same ``load_panel_with_split`` / placebo machinery production
runs use — without actually training a model.

A training-dependent smoke (the actual `python -m renquant_model_patchtst.research
--phase range_find --dataset tests/data/smoke_panel.parquet ...` command) is
the operator's job; that needs torch and 1-5 minutes of CPU. These tests
run in milliseconds and gate every PR.

Pinned invariants:

  1. Fixture has a real signal — per-day Spearman(alpha_signal, label) IC
     mean > 0.25, ensuring a competent ranker can learn it.
  2. Noise features have IC near zero — confirms the fixture isn't
     trivially solvable.
  3. The PR #9 timeshift-placebo cross-split-leak guard holds on this
     fixture: shift(-10) should drop ALL train rows whose shifted source
     would otherwise be in val/embargo. After shift, train rows are still
     well-formed (no NaN labels survive) and val rows are byte-identical
     to the pre-shift run.
  4. Shuffle-label placebo keeps val labels aligned (PR #9 invariant).
  5. csrank_norm + train-fit winsor preserve the per-day cross-section
     structure that the model learns from.

If any of these break, Phase A.0's kill-gate semantics are no longer
trustworthy — the fixture itself must be regenerated or the data pipeline
must be debugged before any model number derived from it is meaningful.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest
from scipy.stats import spearmanr

import renquant_model_patchtst.hf_trainer as hf


# Synthetic fixture files committed to the repo so the smoke runs in CI / on
# CPU without external data. Regenerated by tests/data/_regen_smoke_panel.py.
_TESTS_DATA = Path(__file__).resolve().parent.parent / "data"
SMOKE_PANEL = _TESTS_DATA / "smoke_panel.parquet"
SMOKE_SPY = _TESTS_DATA / "smoke_spy.parquet"


def test_smoke_fixture_files_exist() -> None:
    assert SMOKE_PANEL.exists(), (
        f"missing {SMOKE_PANEL}. Regenerate via "
        f"`PYTHONPATH=src python tests/data/_regen_smoke_panel.py`."
    )
    assert SMOKE_SPY.exists(), (
        f"missing {SMOKE_SPY}. Regenerate via same script."
    )


def _signal_per_day_ic(df: pd.DataFrame, signal_col: str, label_col: str) -> list[float]:
    out: list[float] = []
    for _, g in df.groupby("date"):
        if len(g) < 2:
            continue
        rho, _ = spearmanr(g[signal_col], g[label_col])
        if np.isfinite(rho):
            out.append(float(rho))
    return out


def test_smoke_fixture_has_learnable_signal() -> None:
    """The signal feature MUST drive the label cross-sectionally. If this
    breaks, the fixture is trivially solvable (or trivially unsolvable)
    and Phase A.0's kill-gate semantics no longer work."""
    df = pd.read_parquet(SMOKE_PANEL)
    ics = _signal_per_day_ic(df, "alpha_signal", "fwd_5d_excess")
    mean = float(np.mean(ics))
    assert mean >= 0.25, (
        f"signal IC mean is {mean:+.4f} — fixture's signal-to-label "
        f"relationship is too weak. Check SIGNAL_TO_LABEL_BETA in "
        f"_regen_smoke_panel.py or regenerate."
    )


def test_smoke_fixture_noise_features_have_no_signal() -> None:
    """Noise features must be uninformative cross-sectionally. If any
    noise feature shows IC > 0.1 mean, the fixture isn't isolating signal
    from noise and Phase A.0 placebo gates will mis-attribute."""
    df = pd.read_parquet(SMOKE_PANEL)
    noise_cols = [c for c in df.columns if c.startswith("noise_")]
    assert noise_cols, "no noise features in fixture"
    for col in noise_cols:
        ics = _signal_per_day_ic(df, col, "fwd_5d_excess")
        mean = abs(float(np.mean(ics)))
        assert mean < 0.10, (
            f"noise feature {col} has |IC mean| = {mean:.4f} — should be "
            f"near zero. Fixture may need a longer N_DATES for noise to "
            f"average out, or the seed needs to change."
        )


def test_smoke_fixture_split_partitions_cleanly(tmp_path: Path) -> None:
    """load_panel_with_split with cut='all' on the fixture must produce a
    non-empty train + val + (optional) embargo + test partition. Validates
    the splitter contract on the fixture's date density."""
    # Copy the parquet into tmp_path so load_panel_with_split's relative-
    # path-isms don't interfere.
    dest = tmp_path / "panel.parquet"
    dest.write_bytes(SMOKE_PANEL.read_bytes())
    panel, feat_cols = hf.load_panel_with_split(
        dest, "all", "fwd_5d_excess",
        preprocess=False, val_tail_pct=0.10, embargo_days=5,
    )
    splits = panel["split_label"].value_counts().to_dict()
    assert splits.get("train", 0) > 0
    assert splits.get("val", 0) > 0
    # 'embargo' may or may not be in the dict depending on dates
    assert {SIGNAL_FEATURE := "alpha_signal"} <= set(feat_cols)


def test_smoke_fixture_timeshift_placebo_no_cross_split_leak(tmp_path: Path) -> None:
    """PR #9 invariant on the smoke fixture: after shift(-N), no train
    row should carry a label whose source row was in val/embargo. Uses the
    sentinel-label technique (train→0, non-train→999)."""
    dest = tmp_path / "panel.parquet"
    df = pd.read_parquet(SMOKE_PANEL)
    df.to_parquet(dest, index=False)

    # Learn the splitter's partition by loading once without shift.
    base, _ = hf.load_panel_with_split(
        dest, "all", "fwd_5d_excess",
        preprocess=False, val_tail_pct=0.10, embargo_days=5,
    )
    # Rewrite the panel: label = 0.0 on train rows, 999.0 on non-train rows.
    sentinel = base["split_label"].map(lambda s: 0.0 if s == "train" else 999.0)
    rewritten = base.assign(fwd_5d_excess=sentinel.values)
    rewritten.to_parquet(dest, index=False)

    # Reload with timeshift placebo. Cross-split-leak guard from PR #9
    # must drop any train row whose shift(-10) lands in non-train.
    shifted, _ = hf.load_panel_with_split(
        dest, "all", "fwd_5d_excess",
        preprocess=False, val_tail_pct=0.10, embargo_days=5,
        label_shift_days=10,
    )
    train_labels = shifted.loc[shifted["split_label"].eq("train"), "fwd_5d_excess"]
    leaked = int((train_labels == 999.0).sum())
    assert leaked == 0, (
        f"PR #9 invariant violated on smoke fixture: {leaked} train rows "
        f"carry the val/embargo sentinel after shift(-10)"
    )


def test_smoke_fixture_shuffle_placebo_preserves_val_labels(tmp_path: Path) -> None:
    """PR #9 sibling invariant: shuffle-label placebo permutes ONLY train
    labels; val labels are byte-identical to the un-shuffled load."""
    dest = tmp_path / "panel.parquet"
    dest.write_bytes(SMOKE_PANEL.read_bytes())

    base, _ = hf.load_panel_with_split(
        dest, "all", "fwd_5d_excess",
        preprocess=False, val_tail_pct=0.10, embargo_days=5,
    )
    shuffled, _ = hf.load_panel_with_split(
        dest, "all", "fwd_5d_excess",
        preprocess=False, val_tail_pct=0.10, embargo_days=5,
        shuffle_labels=True,
    )
    base_val = base.loc[base["split_label"].eq("val"), "fwd_5d_excess"].to_list()
    shuffled_val = shuffled.loc[shuffled["split_label"].eq("val"), "fwd_5d_excess"].to_list()
    assert shuffled_val == base_val, (
        "shuffle-label placebo mutated val labels — PR #9 invariant broken"
    )
