"""GOAL-4 Phase-0 — the empirical false-positive calibration prerequisite 1 demands.

WHY THIS EXISTS
---------------
`doc/design/2026-07-30-goal4-power-wall.md` lists, as prerequisite 1 before ANY of
options A-D can be scored:

    "A dependence-preserving null — moving-block or circular-block bootstrap over
     the per-date statistic series, block length justified against the score's
     measured autocorrelation — plus a documented exchangeability argument or an
     empirical false-positive calibration at the realised geometry."

Review said the same thing three times, and it was right each time: the within-date
permutation preserves the *label* overlap but destroys the score's *across-date*
autocorrelation, so `P95_null = 1.9131` was never established as a valid bar.

This module supplies the second half of that prerequisite — the **empirical
false-positive calibration at the realised geometry** — and it needs no model of the
dependence at all, because the screen persisted its own per-date statistic series.

WHAT IT DOES NOT DO
-------------------
It does **not** re-run, revive, or re-score the Phase-0 screen. The screen's result is
UNRESOLVED and stays UNRESOLVED; `t = -1.0025` must not be cited as evidence against an
ensemble under any bar this module produces. What is measured here is a property of the
**harness geometry** — what a bar of 2.3646 over 8 contiguous 60-day blocks really costs
when the per-date series has the dependence this one actually has.

THE NULL
--------
A **circular block bootstrap** over the observed per-date series, recentred to mean
zero. Recentring makes it a null series; resampling in blocks carries the observed
serial dependence into every replicate, which is exactly the property a within-date
permutation lacks.

**Block length is swept, not chosen.** Picking one `b` after seeing the answer is a
researcher degree of freedom; a sweep over `b` spanning the measured dependence range
lets the reader see whether the conclusion depends on it. The measured autocorrelation
of the real series is printed alongside so the sweep can be judged against it.

**What the null inherits.** Bootstrapping the *observed* series means the null carries
whatever dependence is in that series, including any generated by a real effect. That is
the conservative direction for a size measurement and it is stated rather than hidden.

UNITS
-----
`g` is the screen's own ensemble-gain statistic, in IC units. So unlike a geometry-only
calibration, the MDE here is directly comparable to a plausible gain.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

# --- the executed geometry, from the screen's own results.json ---------------
N_EVAL = 508          # .main.N_eval
N_BLOCKS = 8          # .main.n_blocks
BLOCK_L = 60          # frozen prereg: contiguous blocks of 60 trading days
LABEL_H = 60          # frozen prereg: 60-day forward label
T_CRIT_EXECUTED = 2.3646242515927844   # .main.T_crit  (t(0.975, 7))
P95_NULL_WITHDRAWN = 1.9131070060649797  # .main.P95_null — WITHDRAWN, shown for contrast

ALPHA = 0.05
POWER_TARGET = 0.80
BLOCK_SWEEP = (20, 40, 60, 90, 120)


def load_series(path: Path) -> np.ndarray:
    s = pd.read_csv(path, index_col=0).iloc[:, 0].to_numpy(dtype=float)
    if not np.isfinite(s).all():
        raise ValueError(f"{path}: non-finite values in the per-date series")
    return s


def autocorr(x: np.ndarray, lags) -> dict[int, float]:
    d = x - x.mean()
    den = float((d * d).sum())
    return {k: float((d[k:] * d[:-k]).sum() / den) for k in lags}


def circular_block_resample(rng, x0: np.ndarray, reps: int, b: int) -> np.ndarray:
    """(reps, n) circular block bootstrap replicates of a mean-zero series."""
    n = x0.shape[0]
    k = math.ceil(n / b)
    starts = rng.integers(0, n, size=(reps, k))
    offs = np.arange(b)
    idx = (starts[:, :, None] + offs[None, None, :]) % n     # (reps, k, b)
    return x0[idx.reshape(reps, k * b)[:, :n]]


def block_t(x: np.ndarray, L: int, gap: int) -> np.ndarray:
    n = x.shape[1]
    period = L + gap
    nb = n // period
    if nb < 2:
        raise ValueError(f"L={L} gap={gap} on n={n} leaves {nb} block(s)")
    means = np.stack([x[:, i * period:i * period + L].mean(axis=1)
                      for i in range(nb)], axis=1)
    sd = means.std(axis=1, ddof=1)
    sd = np.where(sd == 0.0, np.nan, sd)
    return means.mean(axis=1) / (sd / math.sqrt(nb))


def n_blocks(n: int, L: int, gap: int) -> int:
    return n // (L + gap)


def crossing(h: int, L: int, gap: int) -> float:
    return min(1.0, max(0, h - gap) / L)


def _size_and_p95(rng, series, reps, b, L, gap, bar):
    x = circular_block_resample(rng, series, reps, b)
    t = np.abs(block_t(x, L, gap))
    t = t[np.isfinite(t)]
    return float((t > bar).mean()), float(np.percentile(t, 95)), int(t.size)


def calibrate(rng, x0, reps, b, L, gap):
    """Calibrate at (b, L, gap) AND measure this instrument's own iid baseline.

    The instrument is not exact. A circular block bootstrap at `b = 60` on
    `n = 508` leaves only ~9 resampling units, and repeated blocks widen the null
    even when the input has NO serial dependence at all — so the Student bar
    over-rejects on i.i.d. Gaussian input too.  Reporting a size against a
    nominal 0.05 would therefore charge the data for a distortion the instrument
    introduced.

    Every row carries `size_iid_baseline`, measured by pushing i.i.d. Gaussian
    noise of the same length and dispersion through the IDENTICAL path.  Read
    `size_excess_over_baseline`, not `size_at_student_bar`.
    """
    nb = n_blocks(x0.shape[0], L, gap)
    student = float(stats.t.ppf(1 - ALPHA / 2, nb - 1))
    size, p95, n_valid = _size_and_p95(rng, x0, reps, b, L, gap, student)
    iid = rng.standard_normal(x0.shape[0]) * float(x0.std(ddof=1))
    iid -= iid.mean()
    size_b, p95_b, _ = _size_and_p95(rng, iid, reps, b, L, gap, student)
    return {
        "block_bootstrap_b": b,
        "L": L, "gap": gap, "blocks": nb,
        "crossing": round(crossing(LABEL_H, L, gap), 4),
        "student_bar": round(student, 4),
        "size_at_student_bar": size,
        "size_iid_baseline": size_b,
        "size_excess_over_baseline": round(size - size_b, 4),
        "P95_bootstrap": round(p95, 4),
        "P95_iid_baseline": round(p95_b, 4),
        "n_valid": n_valid,
    }


def power_at(rng, x0, reps, b, L, gap, crit, g):
    x = circular_block_resample(rng, x0, reps, b) + g
    t = np.abs(block_t(x, L, gap))
    t = t[np.isfinite(t)]
    return float((t > crit).mean())


def mde(rng, x0, reps, b, L, gap, crit, grid):
    prev_g, prev_p = 0.0, ALPHA
    for g in grid:
        p = power_at(rng, x0, reps, b, L, gap, crit, g)
        if p >= POWER_TARGET:
            if p == prev_p:
                return g
            return prev_g + (POWER_TARGET - prev_p) / (p - prev_p) * (g - prev_g)
        prev_g, prev_p = g, p
    return None


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--series", type=Path, default=Path(
        "doc/research/data/2026-07-30-goal4-phase0-ensemble-gain/per_date_g_real.csv"))
    ap.add_argument("--reps", type=int, default=4000)
    ap.add_argument("--reps-power", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=20260731)
    ap.add_argument("--json-out", default=None)
    a = ap.parse_args(argv)

    x = load_series(a.series)
    if x.shape[0] != N_EVAL:
        raise SystemExit(
            f"series has {x.shape[0]} dates, the executed screen had {N_EVAL} — "
            "this calibration is only valid at the realised geometry")
    x0 = x - x.mean()
    rng = np.random.default_rng(a.seed)

    ac = autocorr(x, (1, 5, 10, 20, 40, 60, 90, 120))
    R = {"series": str(a.series), "n": int(x.shape[0]),
         "mean_g": float(x.mean()), "sd_g": float(x.std(ddof=1)),
         "autocorr": {str(k): round(v, 4) for k, v in ac.items()},
         "executed": {"L": BLOCK_L, "gap": 0, "blocks": N_BLOCKS,
                      "crossing": crossing(LABEL_H, BLOCK_L, 0),
                      "bar_used": T_CRIT_EXECUTED,
                      "P95_null_withdrawn": P95_NULL_WITHDRAWN},
         "reps": a.reps, "seed": a.seed, "sweep": [], "repaired": [], "mde": []}

    print(f"\nGOAL-4 Phase-0 null calibration — {a.series}")
    print(f"  n={x.shape[0]}  mean_g={x.mean():+.6f}  sd={x.std(ddof=1):.6f}")
    print("  measured autocorrelation of the per-date statistic: " +
          "  ".join(f"r{k}={v:+.3f}" for k, v in ac.items()))
    print(f"\nEXECUTED geometry: L={BLOCK_L} gap=0 -> {N_BLOCKS} blocks, "
          f"crossing {crossing(LABEL_H, BLOCK_L, 0):.3f}, bar used "
          f"{T_CRIT_EXECUTED:.4f}")
    print(f"{'b':>5} {'blocks':>7} {'student':>8} {'SIZE':>7} {'iid base':>9} "
          f"{'EXCESS':>8} {'P95_boot':>9}")
    for b in BLOCK_SWEEP:
        row = calibrate(rng, x0, a.reps, b, BLOCK_L, 0)
        R["sweep"].append(row)
        print(f"{b:>5} {row['blocks']:>7} {row['student_bar']:>8.4f} "
              f"{row['size_at_student_bar']:>7.4f} {row['size_iid_baseline']:>9.4f} "
              f"{row['size_excess_over_baseline']:>+8.4f} {row['P95_bootstrap']:>9.4f}")

    print("\nREPAIRED geometries (gap >= h), same series, b = 60")
    print(f"{'design':>16} {'blocks':>7} {'cross':>6} {'student':>8} "
          f"{'SIZE':>7} {'iid base':>9} {'EXCESS':>8}")
    for L, gap in ((60, 60), (40, 60), (30, 60)):
        row = calibrate(rng, x0, a.reps, 60, L, gap)
        R["repaired"].append(row)
        print(f"{('L=%d gap=%d' % (L, gap)):>16} {row['blocks']:>7} "
              f"{row['crossing']:>6.3f} {row['student_bar']:>8.4f} "
              f"{row['size_at_student_bar']:>7.4f} {row['size_iid_baseline']:>9.4f} "
              f"{row['size_excess_over_baseline']:>+8.4f}")

    print("\nMDE in the screen's own gain units (IC), at the BOOTSTRAP-calibrated bar")
    grid = [0.002, 0.005, 0.01, 0.02, 0.03, 0.05, 0.07, 0.10, 0.15, 0.20,
            0.30, 0.50]
    for label, L, gap in (("executed L=60 gap=0", BLOCK_L, 0),
                          ("repaired L=60 gap=60", 60, 60),
                          ("repaired L=30 gap=60", 30, 60)):
        row = calibrate(rng, x0, a.reps, 60, L, gap)
        crit = max(row["P95_bootstrap"], row["student_bar"])
        m = mde(rng, x0, a.reps_power, 60, L, gap, crit, grid)
        R["mde"].append({"design": label, "crit": crit,
                         "mde_ic": None if m is None else round(m, 5)})
        print(f"  {label:<22} bar={crit:>7.4f}  MDE="
              f"{'>0.50' if m is None else f'{m:.5f}'}")

    if a.json_out:
        Path(a.json_out).write_text(json.dumps(R, indent=2), encoding="utf-8")
        print(f"\nwrote {a.json_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
